#ifndef CTOY_CHUNK_H
#define CTOY_CHUNK_H

#include "common.h"
#include "opcodes.h"
#include "value.h"
#include "object.h"
#include "table.h"

typedef struct {
	int capacity;
	int count;
	uint8_t* code;

	int* lines; //for showing errors
	ValueArray constants; //literals like numbers, varnames
	Table strings; //track the Toy strings used in this chunk
	Object* objects; //track the memory generated by this chunk
} Chunk;

void initChunk(Chunk* chunk);
void freeChunk(Chunk* chunk);
void writeChunk(Chunk* chunk, uint8_t byte, int line);
void writeChunkLong(Chunk* chunk, uint32_t val, int line);

//utilities
uint32_t pushConstant(Chunk* chunk, Value value);
uint32_t writeConstant(Chunk* chunk, Value value, int line);

#endif
