name: C/C++ CI

on:
  push:
    branches: [ 0.4.0 ]
  pull_request:
    branches: [ 0.4.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
